---
- name: Build Pip trusted hosts
  blockinfile:
    path: /root/.config/pip/pip.conf
    block: |
[global]
trusted-host = pypi.python.org
 	             pypi.org
               files.pythonhosted.org


- name: Install prerequisites
  pip: 
    name: "{{ item }}" 
    state: present
  with_items:
    - requests
    - importlib
    - PyYAML
- name: Install ibmsecurity
  pip:
    name: git+https://github.com/IBM-Security/ibmsecurity.git
    state: present