---
- name: Build Pip trusted hosts
  copy:
    src: files/pip.conf
    dest: ~/.config/pip/ #This is being run local anyway
        
- name: Install prerequisites
  pip: 
    name: "{{ item }}" 
    state: present
  with_items:
    - requests
    #- importlib #Installed with 2.7 by default
    - PyYAML
- name: Install ibmsecurity
  pip:
    name: git+https://github.com/IBM-Security/ibmsecurity.git
    state: present

- name: Create Symbolic Link
  file: 
    src: /usr/bin/python2.7
    dest: /usr/local/bin/python2.7
    state: link
