---
##Install and configure CNTLM
- name: install cntlm
  package: 
    name: cntlm
    statue: present
    update_cache: true

- name: install cntlm.conf
  template:
    src: cntlm.conf.j2
    dest: /etc/cntlm.conf
    backup: yes 

- name: start cntlm
  service:
    name: cntlm
    state: restarted